name = "roadworld-blackroad"
main = "src/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
[[routes]]
pattern = "roadworld.blackroad.io/*"
zone_name = "blackroad.io"
[vars]
ENVIRONMENT = "production"
SERVICE_NAME = "roadworld"
VERSION = "2.0.0"
[[kv_namespaces]]
binding = "STORE"
id = "f276921ecd0049d0b0e279338249b93e"
[ai]
binding = "AI"
[[d1_databases]]
binding = "DB"
database_name = "blackroad-os-main"
database_id = "e2c6dcd9-c21a-48ac-8807-7b3a6881c4f7"
